### ISSUE TITLE
[task] 교인 리스트 출력 (Front-end)

### ISSUE THREAD

**Issue by gyounlee** [jibyun/digital-okcc#10]
서버에서 가져온 데이터를 브라우저에 출력.
복잡한 기능은 다음 release에서 구현되도 상관없으니 단순히 리스트를 보여주는데 집중.
레코드가 많을 경우 pagenation으로 할지 아니면 scroll buffer를 사용할 지 담당자가 결정.

**Comment by kwkim80** [comment]
1. views/saint/  하단의 index.blade.php 생성
2. controller에서 보내준 saint list를 뷰에 표시
3. to do: 디자인 작업
4.. 리스트 데이터를 view에서 그리드 형식으로 보여줄 때, filtering, paging,ordering,searching,그리드 결과 다른파일로 저장, 관련해서 그리드 기능과 방향을 논의 필요

**Comment by lifeisox** [comment]
Eloquent ORM을 사용하는 방식으로도 테스팅해보고, Pagination과 Searching은 클라이언트 단에서 JavaScript나 PHP를 사용해서도 편리하게 하는 것 같더라구요. 함께 연구해 보죠.

**Comment by lifeisox** [comment]
Eloquent ORM 방식으로 교인 리스트 출력 완성하여 branch에 push하였습니다.

**Comment by gyounlee** [comment]
프로젝트의 리뷰단계는 현재 code review(pull request) 중인  task에 해당됩니다.
이미 개인적으로 구현해 보셨지만 실제 project에 해당되는 작업은 아닌 관계로 In Progress 또는 To do로 옮겨주시기 바랍니다.

**Comment by lifeisox** [comment]
그럼, 이 타스크는 이제 끝났으니 삭제하는 것으로 하시죠.

**Comment by gyounlee** [comment]
예?  이거 아직 시작 안한 task인데요?
혹시 test가 끝난다고 말씀하시는 거면, 어차피 새로 생성해야 하니, 이걸로 계속 작업해도 될꺼 같습니다.

**Comment by gyounlee** [comment]
간단하게 교인리스트 출력하는 table 구현
