### ISSUE TITLE
[task] 불필요한 파일들 삭제

### ISSUE THREAD

**Issue by gyounlee** [jibyun/digital-okcc#11]
현재 master에 commit 되어 있는 파일 중에 필요없는 파일들 삭제.
에를 들어 storage directory.

**Comment by lifeisox** [comment]
어제 서버에 올리며 테스트해 보았습니다.

현재로선 vendor 디렉토리만 불필요하네요. 테스팅서버가 SSH access를 지원해서 putty 단말기를 통해 명령어를 입력할 수 있었습니다. <span style="color: red">**composer install**</span>

storage 디렉토리도 자동으로 재생성이 되기는 하는데 URL을 통해 웹사이트 접근할 대 에러가 발생하였습니다. 아마도 storage 내부에 중요한 쿠키 정보가 있는 듯... 이것에 대한 정보가 없네요.

.env에 있는 APP_KEY는 **php artisan key:generate** 로 재생성할 수 있습니다.

따라서 현재 결론은 'vendor 디렉토리는 공유할 필요가 없다' 입니다. :sweat:

**Comment by gyounlee** [comment]
수고하셨어요.
서버에 올릴 package는 deploy용으로 새로 구성하는게 좋을 듯합니다.  아마도 deploy라는 디렉토리를 새로 만들어서 그곳에 필요한 파일을 모두 보관해야 할지 아니면 스크립트를 하나 짜서 자동으로 필요한 파일만 업로드 하게 하던지..
master는 코드 공유 목적이니 몇몇 폴더나 파일들이 불필요해 보여서 이 테스크를 만들었습니다.
예를 들어 storage나 vendor 폴더 같은 경우 개발자 각자의 machine에서 생성할 수 있고 굳이 공유할 필요가 없으니 master에 있을 필요가 없고, composer.lock은 잘 모르겠는데, yarn.lock 같은 경우는 자동으로 생성되는 파일이니 이것도 공유할 필요가 없거나 gitignore에 추가해서 불필요한 없데이트를 막아야 겠죠.

**Comment by gyounlee** [comment]
- vendor
- store
- .env
- .env.example
- composer.lock
- tests
삭제
