### ISSUE TITLE
프로젝트 스케쥴

### ISSUE THREAD

**Issue by gyounlee** [jibyun/digital-okcc#14]
Project Name : Digital OKCC
<table>
  <tr>
    <th>Release</th>
    <th>기간</th>
    <th>작업목록</th>
    <th>세부항목</th>
  </tr>
 <tr>
    <td rowspan=8>Release 1</td>
    <td rowspan=8>미정</td>
    <td rowspan=3>개발환경 설정</td>
    <td>GitHub Setting</td>
  </tr>
  <tr>
    <td>테스트 서버 Setting</td>
</tr>
  <tr>
    <td>Laravel 서버에 테스트 해보기</td>
</tr>
  <tr>
    <td rowspan=5>주소록 출력</td>
    <td>주소록 DB 설계</td>
</tr>
  <tr>
    <td>테스트 데이타 생성</td>
</tr>
  <tr>
    <td>전체 화면 frame 구성</td>
</tr>
  <tr>
    <td>Header/Footer 디자인</td>
</tr>
  <tr>
    <td>주소록 리스트 가져와서 출력하기</td>
</tr>
  <tr>
    <td rowspan=8>Release 2</td>
    <td rowspan=8>미정</td>
    <td rowspan=3>로그인 기능 </td>
    <td> 로그인 화면 디자인 </td>
</tr>
  <tr>
    <td>유저 등록 flow 구상</td>
</tr>
  <tr>
    <td>로그인 기능 구현</td>
</tr>
  <tr>
    <td rowspan=3>주소록 입력/수정/삭제</td>
    <td>입력화면</td>
</tr>
  <tr>
    <td>수정화면</td>
</tr>
  <tr>
    <td>삭제화면</td>
</tr>
<tr>
    <td>관리자 페이지</td>
    <td>관리자 페이지 구성</td>
</tr>
  <tr>
    <td>Reporting 기능</td>
    <td>주소록 Reporting</td>
</tr>
  <tr>
    <td>Release 3</td> 
    <td>미정</td> 
    <td>심방관리 기능</td> 
    <td>TODO</td>
</tr>

</table>

**Comment by gyounlee** [comment]
추가할 내용이나 변경할 내용있으면 자유롭게 comment 달아주세요.
만약 문제없으면 Approve 또는 good to go  아님 좋아요.. 등 뭐든 찬성한다는 메시지 남겨주세요.

**Comment by lifeisox** [comment]
저희가 개발하는 것이 일종의 업무용 소프트웨어라 릴리즈1이나 2에서 Reporting tool 을 envisioning하고 갔으면 합니다. 주소록 출력을 PDF와 EXCEL로 테스트 해보는 방식으로요.

Laravel Report Generators (PDF & Excel) : [https://github.com/Jimmy-JS/laravel-report-generator](url)
Rapidly Generate Simple Pdf Report on Laravel (Using barryvdh/laravel-dompdf or barryvdh/laravel-snappy) or Excel Report (using Maatwebsite/Laravel-Excel)
This package provides a simple pdf & excel report generators to speed up your workflow

**Comment by gyounlee** [comment]
Reporting Tool Release 2에 반영했습니다.

**Comment by lifeisox** [comment]
Approve
