### ISSUE TITLE
Bootstrap table Toolbar / custom search

### ISSUE THREAD

**Issue by gyounlee** [jibyun/digital-okcc#140]
- bootstrap table에서 custom toolbar의 버튼들이 오른쪽으로 정렬되어 search box 바로 전에 위치할수 있게 구현.
-  custom search function을 만들어서 현재 visible 한 column에 대해서만 search 할수 있게 구현

**Comment by gyounlee** [comment]
@lifeisox 혹시 시간나시면 이것 좀 연구해 주세요.   꼭 필요한 기능은 아니지만 있으면 유용할꺼 같네요.

**Comment by lifeisox** [comment]
@gyounlee 지금 현재 visible 한 컬럼에 대해서만 search하게 되어 있습니다. 다만, 사용자가 동적으로 visible을 바꿨을 때 search 필드로 적용될지 안될지 dynamic하게 변경되는 부분은 구현하지 않았습니다. (구현 방법은 예측할 수 있지만... 많이 쓰일 것 같지 않아서 구현 안한 부분입니다)

오른쪽 정렬은 연구해 볼께요. (페이지 Title을 상단 왼쪽(admin 참조)에 넣을 때 custom toolbar를 오른쪽 정렬하게 되면 design이 좀 우스깡 스럽게 보일 것 같아 시도해 보지 않았습니다.

**Comment by lifeisox** [comment]
@gyounlee 일단 Custom Toolbar를 Search Box 왼쪽에 위치하는 것 완료하여 steve-test로 push 하였습니다.

**Comment by lifeisox** [comment]
@gyounlee custom search funtion은 정확히 원하시는 것이 무엇인지 몰라 안했어요. 제가 위에 올린 글 참조해서 다른 기능을 원하시는거면 말씀해 주세요.

**Comment by gyounlee** [comment]
bootstrap table에 각 column마다 search 가능한 field인지 아닌지 설정하는 기능이 있어서 그걸 설정해 놓으신 걸로 알고 있어요.
그런데 위에 말씀하신거 처럼 사용자가 visible column을 변경하면 여전히 화면에 없는 데이타를 검색하는 문제가 발생합니다.
bootstrap table 메뉴얼에 보니 customSearch 기능이 있던데 이게 아마도 search function을 직접 구현가능하게 제공하는 기능으로 보입니다.  
이 기능을 활용하면 현재 화면에 보여지는 column만 search 할수 있게 만들수 있을꺼 같아요.

**Comment by lifeisox** [comment]
Search 기능을 이용할만한게 Member 밖에 없어서. 별로 신경쓰지 않았네요. 이 기능 구현하는 것으로 하죠.

**Comment by lifeisox** [comment]
완벽 구현 완료
