### ISSUE TITLE
GUI 디자인 리뷰 절차

### ISSUE THREAD

**Issue by gyounlee** [jibyun/digital-okcc#16]
MockupBuilder 프로그램이 설치 안되는 경우도 있고, 어쩌면 이 방법이 좀 복잡하고 귀찮을 수 있다는 생각이 들어 GUI 디자인 후 각자가 어떤 방법으로 리뷰할 지 의견을 묻습니다.
제가 몇가지 경우를 나열해 봤고, 다른 의견이 있으시면 댓글 달아주세요.

1. GUI Mockup을 툴을 이용하여 그린 후 리뷰한다.
2. 스크린 캡처 후 그림판 같은 툴을 사용하여 간단히 수정하여 리뷰한다.
3. 직접 코드를 리뷰한다.
4. 화상 통화시 모니터 화면은 share 하여 리뷰한다.
5. 기타등등

**Comment by lifeisox** [comment]
요즘에는 집사님께서 사용하려고 하는 mockup website design tool을 사용 안하는 것 같아요. 웹사이트 디자인이 너무 쉬워졌기 때문인 것 같아요. 실제로 Wix나 Wordpress를 사용하면 엄청난 템플릿이 있기 때문이죠. 그러니, 일단 디자인 단계에서는 각자 원하는 샘플 웹페이지를 찾아 캡쳐하여 올려 리뷰하던가 아니면 손으로 그려 스캔 받은 그림으로 리뷰하는 것이 어떤가요?

**Comment by gyounlee** [comment]
예. 좋습니다.  제가 소개한 그 툴도 하나의 방법이고 이런식으로 mockup을 그려서 리뷰하자는 게 목적이었습니다.
다들 이 의견 찬성하시죠?
현재 #6 task가 김집사님 한테 assign 되어 있는데, 혹시 다른 task 작업 중이시면 unassign 하시면 되고, 아니면 구상하시는 frame 하나 올려주세요,  그럼 다 같이 리뷰하죠.

**Comment by gyounlee** [comment]
어제 회의에서 기본적인 화면 layout은 논의가 됐고, 회의시 참조했던 파워포인트는 master에 올려놓겠습니다.
해당 layout은 정선영 집사가 좀 더 보강할 예정이고 sitemap도 작성할 예정입니다.
어느 정도 큰 틀은 잡혔으니 master page나 header/footer의 초기버전 정도는 코딩 가능하리라 생각됩니다.

어떤 특정 부분의 GUI 리뷰는 issue를 생성하여 거기에 이미지를 업로드 하여  다 같이 리뷰하는 것으로 하겠습니다.
