### ISSUE TITLE
Bootstrap Table Test (교인 리스트 출력)

### ISSUE THREAD

**Issue by lifeisox** [jibyun/digital-okcc#17]
Eloquent ORM과 Bootstrap Table을 사용하여 교인 리스트 출력을 구현하여 branch에 push 하였습니다.

1. Searching 기능
2. Sorting 기능
3. Pagination
4. Excel Export (이 부분을 구현하다 라라벨 프레임워크와의 버그가 있어 중단하였음)

**Comment by gyounlee** [comment]
프로젝트의 리뷰단계는 현재 code review(pull request) 중인  task에 해당됩니다.
혹시 개인적인 test 목적의 task이고 이미 완료된 작업이면 Done으로 옮겨주시기 바랍니다.
