### ISSUE TITLE
lang.js 404 (not found) issue

### ISSUE THREAD

**Issue by gyounlee** [jibyun/digital-okcc#187]
이 에러가 공통적으로 발생하는 에러인지 확인 부탁드려요.
![image](https://user-images.githubusercontent.com/3138969/40562386-adba0cea-602e-11e8-9a78-b425e7ffa230.png)

**Comment by lifeisox** [comment]
@gyounlee 집사님께서 .js 에서 localication 사용할 수 있도록 한 모듈을 추가하셨는데 master.blade.php에 <script src="/js/lang.js"></script> 을 추가해야할거예요. 집사님께서 보내주신 url 보고 저도 구현하였는데 이 script 라인을 넣으라고 되어 있어요. 근데 안 넣으셨길래 그래도 되는줄 알았죠.

**Comment by gyounlee** [comment]
DocumentRoot issue.
