### ISSUE TITLE
도메인 검색 및 계약

### ISSUE THREAD

**Issue by lifeisox** [jibyun/digital-okcc#20]
OCO를 서비스하기 위한 도메인이 필요합니다. 현재 okcc.ca 도메인이 살아 있어 담당장로인 이인원 장로에게 계약 승인 의뢰를 한 상태입니다.

도메인을 계약하게 되면
홈 페이지(추후 개발 가정): okcc.ca
OCO: oco.okcc.ca 또는 it.okcc.ca
등 서브 도메인을 만들어 우리 프록램을 설치하면 됩니다.

혹시 계약 가능한 더 좋은 도메인이 있거나, 다른 의견 있으면 의견 주세요.

**Comment by lifeisox** [comment]
일단 이인원 장로의 승인으로 okcc.ca 도메인 계약을 완료했습니다.

다른 도메인을 사용하자는 의견이나, 제안 사항 있으면 개진 바랍니다.

**Comment by gyounlee** [comment]
이인원 장로님이 좋아하시더라구요.   좋은 도메인 확보 감사.

**Comment by lifeisox** [comment]
더 이상 의견 업스면 이 타스크는 Close합니다.
