### ISSUE TITLE
Side-Bar 스크롤 바 issue

### ISSUE THREAD

**Issue by gyounlee** [jibyun/digital-okcc#26]
side-bar menu에 항목들이 늘어나면 side-bar 자체에 스크롤바가 생기지 않고 전체 화면에 스크롤 바가 생김.
side-bar 자체에 스크롤바가 생기도록 수정
![scrollbarissue](https://user-images.githubusercontent.com/3138969/38315946-91cde376-37f7-11e8-978d-04344943e822.png)

**Comment by jibyun** [comment]
이건 버그보다는 유저의 선호 방식의 차이가 아닐지요? 제 개인적으로는 side-bar에 스크롤은 좀 지저분해 보이고 불편하더라구요. 전체화면 스크롤로 mouse pointer가 browser위 어디에 있던지 mouse wheel를 써서 바로 화면을 올라갔다 내려갔다 할 수 있는게 제가 선호하는 방식이거든요. ^^ 의견들이 어떠신지요?

**Comment by gyounlee** [comment]
제가 생각했던 화면구조는 전체 스크롤바가 아닌 메인 컨덴츠와 메뉴바에만 스크롤이 생기는 구조였습니다.  그래서 헤더와 푸터가 늘 고정되어 있는 형태를 생각했습니다.  
화면 기획서도 데쉬보드 형태이고, 또 블로그나 웹사이트가 아닌 업무용 웹어플리케이션이라 이런 방식으로 동작할꺼라 생각했었어요.    
제가 생각했던 방식으로 갈꺼면 스크롤바는 왼쪽과 메인각각 가져야하고, 그렇지 않다면 전체 스크롤바가 맞다는게 제 의견입니다.

**Comment by lifeisox** [comment]
header, footer는 간단히 고정되지만 사이드바 나누려면 구성을 완전히 바꿔야죠...

**Comment by gyounlee** [comment]
버그가 아닌 걸로 결정.
