### ISSUE TITLE
MemberListService: 검색분류항목 

### ISSUE THREAD

**Issue by gyounlee** [jibyun/digital-okcc#30]
교인검색 화면의 왼쪽 sidebar에 보여질 검색 category를 DB로 부터 읽어와서 객체를 리턴한다.

- Function name: MemberListService::buildCategory()
- Input: 없음
- Output: Hierarchical 구조의 object.
- Object의 속성: 
-- text: (화면에 출력될 이름)
-- code: (code 번호)
-- selectable: (true/false - 일단 leaf node만 true)
-- children: (child object 배열)

- Sample object:

$myObj1 = (object)array();
$myObj2 = (object)array();
$myObj3 = (object)array();
$myObj1->text = "직분";
$myObj1->code = "1111";
$myObj1->selectable = false;
$myObj2->text = "목사";
$myObj2->code = "1112";
$myObj2->selectable = true;
$myObj3->text = "부목사";
$myObj3->code = "1113";
$myObj3->selectable = true;
$myObj1->children = array($myObj2, $myObj3);

- Test 방법: RestfulApi GET (/api/okcc/category )
JSON 데이타를 확인한다.
ex)
`[{"text":"전교인","code":1111,"selectable":false},{"text":"직분","code":2222,"selectable":false,"children":[{"text":"교육목사","code":2224,"selectable":true},{"text":"시무장로","code":2225,"selectable":true}]}]`

**Comment by kwkim80** [comment]
![image](https://user-images.githubusercontent.com/37365897/38462981-2a6c1522-3abd-11e8-88eb-98b9f985b1d7.png)

혹시 이 사이드 바와 매치되는 배열을 구성해달라는 말씀이신거죠?

**Comment by gyounlee** [comment]
맞아요.  JSON데이터를 이용해서 화면에 뿌려줄꺼예요.
