### ISSUE TITLE
[task] 교인명부 DB 설계

### ISSUE THREAD

**Issue by gyounlee** [jibyun/digital-okcc#4]

**Comment by gyounlee** [comment]
교인 명부 (주소록) 관련된 DB 테이블 schema가 output으로 나와야 합니다.
Output은 꼭 코드 형식일 필요는 없습니다.  master에 저장될 내용이니 파일을 생성하여 pull request 하시면 다같이 review 하겠습니다.

**Comment by gyounlee** [comment]
어제 회의내용을 바탕으로 DB table schema를 구상하여 다이어그램을 만들어서 리뷰하겠습니다.

**Comment by gyounlee** [comment]
현재 ERDPlus 라는 사이트를 통해 diagram을 그리고 있습니다.  혹시 써보신 분이나 문제있었던 적 있으면 알려주세요.

**Comment by gyounlee** [comment]
DB Diagram의 초기버전입니다.   더 수정이 필요하고, 수정되는 데로 계속 업데이트 할 예정입니다.

일단 전체적인 구조를 봐주시고, 차근차근 세부적인 내용도 검토 바랍니다.
아래는 PDF파일이고, 작업은 MySQL Workbench에서 했습니다.  workbench 파일은 업로드가 안된네요.. 필요하시면 다른 방법으로 제공하겠습니다.

[Digital_OKCC_DB_Diagram.pdf](https://github.com/jibyun/digital-okcc/files/1864298/Digital_OKCC_DB_Diagram.pdf)

**Comment by lifeisox** [comment]
역시 senior의 향기가 나는군요. 아직 필드명과 정확한 크기, 타입 등은 미정인 것으로 이해했습니다.

family_map (가족관계) associative table에서 가족관계(부모, 형제, 자매, 동거인 등) 필드 추가 검토
member_position (직분) : association table을 만들 필요가 없다고 보여짐, 다중 직분을 가질 경우 없다고 봄
system log를 어느 수준까지 기록할 생각이신지 궁금?

이상입니다.

**Comment by lifeisox** [comment]
참, one more thing, 현재 auth test는 라라벨에서 제공한 user table, password_reset table을 사용해서만 테스트해봤는데, 집사님 다이어그램 대로라면 모든 부분을 다시 구현해야할 것 같은데(특히 reset부분) 이 부분 가능한지 테스트가 안되어 있어 혹시 제공되는 테이블을 건드리지 않고 다이어그램을 만드실 생각은 없는지 묻고 싶습니다.

**Comment by gyounlee** [comment]
@lifeisox 답변입니다.
1. 가족관계를 필드 추가하는 건 찬성하고, 필드는 family_map 보다는 member테이블에 뒀으면 합니다.
2. 다중 직분을 가질 가능성이 있어보입니다. 예) 집사이면서 교사, 구역장이면서 장로
    직분과 부서는 일단 member table에도 필드를 두었고, association table도 뒀습니다.  필요에 따라 삭제하면 될꺼 같습니다.
3. 유저 로그인/로그아웃, 데이타 입력/수정/삭제 등.  system_log 테이블을 약간 독립적이라 추후에 변경하기가 쉬울꺼라 예상합니다.
4. laravel에서 기본으로 제공하는 걸로 알고 있습니다.  제가 테스트를 안해봐서 어떤식으로 유저 등록을 받고 로그인을 하는지 확실하지 않은데요, 혹시 이게 사용자를 일단 DB에 무조건 입력하는 방식이라면 전 사용하지 않았으면 합니다.

**Comment by gyounlee** [comment]
[Digital_OKCC_DB_Diagram_V0.2.pdf](https://github.com/jibyun/digital-okcc/files/1864644/Digital_OKCC_DB_Diagram_V0.2.pdf)


새로운 버전 업데이트했습니다.  그리고 간략한 테이블 정보입니다.
수정사항
1. member table의 primary field data type을 tinyint로 변경
2. memo table 생성


테이블 설명
1. family_map: 가족관계를 정의하는 테이블 
PRI_MEMBER필드는 member 테이블 중에서 primary가 true인 member의 ID
SUB_MEMBER필드는 PRI_MEMBER와 가족관계인 member의 ID

2. member_status: 교인의 상태를 정의하는 테이블
회원/비회원/비정기적참석/장기결석/해외거주/전도대상/사망/이명 등등의 value가 입력될 예정

3. member_positon: 교회 직분을 정의하는 테이블
담임목사/부목사/전도사/집사/ 등등

4. member_position_map: member와 position간의 association을 정의
한명이 2개이상의 직분을 가질 경우가 있을 꺼 같아서 생성했음.
예) 집사 이면서 교사, 또는 장로이면서 구역장

5. cell: 구역을 정의하는 테이블
교구와 구역리스트를 모두 이곳 테이블에 저장
LEADER_ID는 구역장, VICE_LEADER_ID는 구역권사 정도..

6. cell tree: 교구와 구역의 계층관계를 정의하는 테이블

7. department: 교회 각 부서를 정의하는 테이블
당회/집사회/성가대/  등등

8. department_tree: 부서의 계층관계를 정의하는 테이블
꼭 필요할지는 모르겠지만 예를 들어 재정부와 서무부가 관리위원회 아래에 있기 때문에 계층관계를 정의하기 위한 
테이블 생성

9. member_dpartment_map: member와 부서간의 association을 정의
한명이 복수의 부서에 소속될 수 있음

10. member_level: 적당한 단어를 몰라서 일단 level이라고 했지만 이건 신급을 정의하는 테이블
세례교인/입교/영세 등등

11. visit: 심방내용을 기록하는 테이블

12. user: 시스템 사용자 ID와 password를 저장하는 테이블
일단 member테이블과 association을 위한 MEMBER_ID 필드를 두었고, RESET 필드는 최초 로그인시 
패스워드변경 필요성을 나타내는 필드

13. Privilege: 유저의 권한 레벨을 정의하는 테이블
슈퍼관리자/관리자/수정가능자/보기만가능한자 등등

14. role: 각각의 권한을 정의하는 테이블
교적부 접근권한/재정부 접근권한/이메일발송권한/등등

15. privilege_role_map: privilege에 복수의 role을 부여하기 위한 mapping table

16. system_log: 각종 유저 activity에 관련된 내용을 저장하는 로그테이블
로그인/로그아웃/데이타 수정등의 내용

17. member_history: 각 member의 약력같은 history를 저장하는 테이블

18. memo: 개인 메모를 기록하는 테이블

**Comment by lifeisox** [comment]
집사님

지금 집사님은 member_position에 직분과 직책을 동시에 넣으시려고 계획하는 모양입니다. 하지만 일반적으로 목사, 장로, 집사 이런거는 직분으로... 성가대장, 구역장, 교구장... 이런 것들은 직책으로 분류하여 기록합니다. 목사님 제안서에 있는 것은 직책을 제외한 직분만 기록한 것으로 보입니다. 직책을 추가할지는 목사님께 문의하여도 되겠지만, 그냥 넣어도 좋을 것 같습니다.

**Comment by gyounlee** [comment]
@lifeisox 아.. 그런거군요.
그럼 직책은 한사람이 여러개 직책을 가질수도 있는 거죠?
사실 이부분이 좀 고민인데, 정선영 집사의 기획안을 보면 남션교회의 경우 회장/총무 등을 구분하게끔 되어있어서 각 부서에 leader field를 둘지 아니면 직책을 따로 만들지 고민입니다. 
일단 직책 테이블을 따로 만드는 걸로 가겠습니다.

**Comment by jibyun** [comment]
다이아그램 자체에 대해서는 이해가 갑니다.  거기에 대해서는 저는 별로 드릴 말씀이 없구요. 몇가지 테이블의 이름을 변경했으면 하고 제안을 하고 싶습니다. cell 대신에  cell_group 이나 small_group이 좀 더 명확하게 테이블을 목적을 구분지을 것 같습니다. 그리고 member_level 대신 membership_level이 어쩔까요? membership이란 단어가 이미 어느 단체에 속해 있다는 곳을 내포에 있거든요.

**Comment by gyounlee** [comment]
@jibyun 어제 미팅에서 목사님이 영어를 기본 언어로 하자고 했어요.  지금 테이블에 _KOR은 그냥 혹시나 해서 내가 집어넣은 거고, 모든 메뉴에서 부터 직책 부서 이름 등 영어가 기본이예요.
종인씨 어깨가 무거워질꺼 같아요.. 흐흐.  대부분 적절한 영문표기는 목사님이 제공할 예정이지만 우리가 native가 아닌지라 사소한 메시지도 영어로 표현하기 힘들어요.
이런 comment 아주 좋습니다.

**Comment by lifeisox** [comment]
라라벨 권고사항이 테이블 명은 복수형으로 모델명은 단수형으로 컨트롤 명은 복수형으로 하는 것입니다. 혹시 이런 것도 리뷰 대상이 된다면 ...  이 룰 을 지키지 않으면 만들 모델 안에 테이블을 연결하는 문장을 한 줄 넣으면 됩니다.

**Comment by gyounlee** [comment]
@lifeisox 아.. 집사님이 어디에다가 그렇게 적어놓으신거 기억나네요.  
이왕이면 룰을 따라야죠.  감사합니다.

그리고, 한가지 질문요.
마이그레이션인가 모델인가 생성하면 앞에 날짜가 파일명에 포함되는데 그거 없엘수 없나요?  좀 보기 이상해서. ㅋㅋ
그리고 이건 아마 @kwkim80 씨가 연구해야 할지도 모르는데, 혹시 호스팅 업체에서 shell을 지원하지 않을 경우 어떻게 migration을 실행해서 db table을 생성할지.  이럴 경우를 대비해서 DDL을 만들어 두는 게 나을지... 뭐 이런 고민이요.

암튼 DB 수정은 기웅씨 feedback 받고 일괄적으로 하겠습니다.

**Comment by lifeisox** [comment]
@gyounlee 직책은 당연히 일 대 다 구요. 테이블에 회장, 부회장 두는 것보다 직책을 받들어 조인하는게 좋아보입니다. 부서별로 직제가 무척 다르기 때문입니다.

**Comment by lifeisox** [comment]
@gyounlee 날짜 정보를 이용해서 롤백을 하던가 하는데 이용한다고 되어 있습니다. 그리고 호스팅 업체로 데이터 옮길 때는 DB 만들고, User 만들고, local에서 export한 다음 서버에서 import하여 인스톨합니다.

**Comment by lifeisox** [comment]
@gyounlee 정집사님 사이트 맵을 방금 봤습니다. 사이드 메뉴의 검색에 관련된 테이블에는 해당 첫화면을 라우팅할 수 있는 주소를 넣을 수 있는 필드를 만들었으면 합니다. 이게 동적인 메뉴라 필요한 것 같습니다.

**Comment by lifeisox** [comment]
@gyounlee 코드 매핑을 위한 테이블(직분, 교인 상태 등)에 대한 제안: 만약 키를 auto increment로 사용하실 계획이시라면, sort 를 위한 필드를 추가할 것을 제안합니다. 화면 입력할 때 매핑테이블은 콤보 박스 형태로 보여지게 되는데, 여기에 보여질 순서를 기록하기 위함입니다. auto increment가 아니라면 관계없습니다. 데이터 입력할 때 추가될 데이터를 예상해서 키의 gap을 두고 입력하면 됩니다.

**Comment by kwkim80** [comment]
일단 교회 운영이 정확히 어떻게 되는지 잘 모르기 때문에 문의사항이 많습니다
나중에 기존 DB를 수정할 필요가 없이 확장성 있게 설계를 하는지 아니면 심플하게 설계해야 하는지 각 항목에 대해서 논의가 필요한지를 서로 공유하기 위해 이 과정을 진행한다고 생각합니다. 그런 의미에서 우리교회에 운영을 잘 모르는 저에게는 더 중요하다고 생각이 드네요.
테이블 통합과 분리, 테이블 추가 생성,  기타 문의, 필드 추가 사항 들에 대해서 나눠서 의견드리겠습니다.

-테이블 통합과 분리
1.  코드테이블 문의
  기존 member position, status,level, privliage, role 테이블이  데이터 테이블이라기 보다는 코드테이블인 것 같습니다. 통합 테이블로 구현하는 의견을 문의 드립니다.  차후 선택코드 들이 추가 될 때(특히 회계 및 재정) , 새로운 테이블을 생성하는 번거로움보다 통합테이블로 처리하면 관리가 쉽고 확장성이 더 좋을 것 같습니다 . 그래서 분리해야 할 테이블은 분리하고, 코드데이터로 사용될 값들은 통합하는 것에 대해서 문의드립니다.
2. department 부서에도 부서장, 부부서장(nullable)을 추가하여 cell 테이블가 통합 의견입니다.
이부분은 통합이 안될 수도 있지만 할려면 또 가능할 것도 같아서 문의 드립니다.
그리고 department 의 type필드를 통합여 cell, 구역,  성가대, 회장단 등의 모든 교회 조직은 통합관리가 가능한지 문의 드립니다. 그리고 department_member_map테이블에서 직책필드도 추가가 필요해보입니다.(김집사님도 같은 의견이 있네요)
이렇게 하면 교회의 모든 행사나 일정을 연결하여 관리하기가 용이할 것 같아서 문의드립니다 

-테이블 생성
3.   user와 privilige 사이에도 맵테이블 주어서 한 사용자가 여러 권한 그룹을 가질수 있도록 할 필요성에 대한 문의입니다. 사용하다보면 Privilege 권한 그룹이 계속 추가될 경우가 있습니다.
권한 그룹이 계층적으로 포함 관계로 만들것인지, 각각의 권한 그룹을  별개로동작하도록 할 경우에는 
다대다의 관계도 될 것 같습니다. 어느 방향으로 갈것인지  문의 드립니다.

4 사이드 메뉴 형태를 보면 menu의 동적 확장성이 필요할 듯 합니다 그리고 차후의 menu를 추가해야 할 경우도 있을 것 같아 menu테이블이 필요하고,url필드도 필요한 것같습니다. 그리고 menu 테이블을 만들면 hierachy하게 만들것인지 , 트리 맵으로  따로 뺄것인지를 문의드립니다. 다만 서로 편한의 기준이 다르지만  저는 menu테이블 자체에서 hierachy하게  하는게 작업진행이 더 편합니다.

5. 메일 발송 히스토리 테이블 생성 필요 문의

6. 공지게시판, 자료실 등 기능 포함 및 게시판 테이블 생성 필요 문의
-분명 차후에 need가 발생할 것 같습니다

7. 부서별 모임 테이블
 -교회 일정 history를 위한 일정 필요성
 - 단체 메일 발송시, 교적부에서 선택가능하지만, 1차2차3차 재발송시, 어떤 entity가 있으면 그룹대상에 대해 재발송이 용이할 것 같은데, 모임 테이블이 괜찮을 것 같은 의견
 -일정 관리
- 심방도 여기에 통합 할 수 있겠지만 분리하는게 좋을 것 같습니다.

8. 심방 및 모임 테이블(미확정)에 대해 참석자 mapping 테이블이  필요 여부
-7 내용과도 비슷한테, 메일발송, 일정공유 및 관리, 히스토리 관리를 위해  기능정의를 어디까지 할 것인지에 따른 필요여부 문의

기능 문의
9. history 기능 문의
 현재 history테이블이 별도록 있어 성도들의 히스토리를 별도 입력하여 관리하도록 되어 있는데
 이부분을 다시 문의드립니다. 특정 내용에 대해서 history가 필요한 것인지 논의가 필요한 것 같습니다.
member position, status,level, department,cell 등의 특정 테이블에서 history를 관리할 것인지 , 아니면 별도 history관리를 할 것인지 문의드립니다. 그리고 특정테이블에서 hisotry관리를 한다면, 그관련 맵테이블에서 시작기간,종료기간을 주어 맵자체에서 히스토리 관리를 하는 방안도 문의드립니다. 이 부분은 제 기억과 이해력이 정확하지 않지만 목사님이 이런 방향으로 얘기하신것이 언뜻 기억납니다. 다른 분의 기억 recall을 요청드립니다.

10 memo, visit쪽의 첨부파일 기능이 필요여부

11.  department, cell 에 대해서 tree table을 별도 생성할 것인지, 자체 hierarchy하게 구성할 것인지 문의

12. menu 접근성 문제 
- 이부분을 role에 넣어서 priviliage별로 메뉴 접근성 관리할지,
- priviliage에 별도로 menu접근성이 설정하기 위한 맵핑테이블을 할지 문의드립니다. 소메뉴까지 별도 접근 권한을 주고 확장성이 크나, 대메뉴로 접근성을 주는 경우에는 불필요

단순필드 추가
13. 혹시 기존 map테이블을 복합키로 갈것인지,별도 primary키를 추가할 것인지.
- mvc에서는 별도 키가 있는게 관리하기 용이해서 문의드립니다.

14. family 맵에서 관계 필드(아들, 딸, 어머니,남편,부인)의 추가 필요성 문의

15. 로그테이블에 타입필드를 추가하여, 예를 들면 로그인,에러, 권한 변경, 기타 등을 두고 관련 내용을 분류할 것인지 문의드립니다.
 차후 로그기록 페이지 나, 권한 변경 을 따로 페이지 구축하고, 테이터 호출시 용이할 것 같아 문의드립니다.

**Comment by lifeisox** [comment]
지금 해당없어보이지만 인쇄나 이메일 발송을 위해 사용자가 대상자를 쉽게 선별할 수 있는 스크립트 Generator와 그 스크립트를 저장할 테이블이 필요합니다.

한번 저장해 놓은 스크립트를 이용해서 계속 인쇄하거나 엑셀로 만들거나 이메일 발송을 할 수 있도록 하기 위함입니다.

**Comment by gyounlee** [comment]
현재까지 개발된 ERD를 commit 하고 close 할 예정.

**Comment by gyounlee** [comment]
[db_schema.pdf](https://github.com/jibyun/digital-okcc/files/2063698/db_schema.pdf)
