### ISSUE TITLE
[task] 전체화면 frame 구성

### ISSUE THREAD

**Issue by gyounlee** [jibyun/digital-okcc#6]
전체적인 화면 디자인
너무 detail 하진 않아도 어떤식으로 화면이 구성될지 대략의 layout이 필요.
GUI Mockup 툴을 사용하면 서로 의논하기 좋을 듯.

**Comment by gyounlee** [comment]
전체적인 화면 구성을 위한 task인데, 아예 초기화면을 디자인 하셨네요.
작성하신 초기화면 나쁘지 않습니다.  약간만 보완하면 이대로 가도 될꺼 같아요.
거기에 앞서 전체적인 화면 구성 (layout, menu, navigation, header, footer) 에 간단하게 나마 결정하고 갔으면 합니다.  예를 들어 직분코드 메뉴를 선택했을 시 네비게이션 바를 보여줄 지, 그리고 메인화면은 1단으로 갈지 2단으로 갈지... 등등
화면 디자인을 어떻게 서로 리뷰할지 고민해 보겠습니다. #

**Comment by lifeisox** [comment]
Header (Navigation, Menu)와 Footer는 항상 보여주는 것이 맞는것 같습니다. 다만 Navigation Bar의 Sign In은 로그인 되었을 경우 사용자 이름으로 보이게 만들 계획이었습니다.

Content 부분은 내용이 무엇인지에 따라 디자인이 바뀔 것 같습니다. 예를들어, 간단한 코드 입력화면과 복잡한 입력 화면, 조회 화면에 따라 디자인이 많이 바뀔 겁니다.

**Comment by lifeisox** [comment]
나는 아직 무슨 화면을 리뷰하자는건지 모르겠어요. 우리가 필요한 화면은 초기 화면과 각 메뉴항목별로 화면이 한개씩 나올텐데 이 중 무슨 화면을 리뷰하는건가요?
예를들어, 우리가 필요한 화면은 초기화면, 단순코드입력화면, 복잡한 사항 입력화면, 조회화면, 인쇄화면 등등이 있을건데 무순 화면을 리뷰하자는건지요.

일단 모든 메뉴가 되었든 메뉴 접근성 때문에 상단에 네비게이션을 두든 좌측이나 우측에 두면 될테고 그 내부에 들어가는 화면은 컨텐츠별로 조금씩 다를 것이 생각합니다.

일단 초기화면 올립니다. 

![image](https://user-images.githubusercontent.com/16562434/37854439-51633ad2-2ec1-11e8-8a52-9525dde37f84.png)

**Comment by lifeisox** [comment]
그리고, 네비게이션 메뉴를 포함한 헤더에는 무슨 내용이 들어갔으면 좋겠구, 하단의 footer에는 무슨 내용이 들어가면 좋을지 함께 논의하면 좋을 것 같습니다.

중간, content 구역에 들어갈 내용은 그때그때 다시 화면 리뷰를 해야 할 것 같습니다.

**Comment by lifeisox** [comment]
디자인을 참조하여 기본 화면을 만들었습니다. 디자인에는 없지만 편의상 <Top> 버튼을 마스터에 추가하였습니다.

**Comment by lifeisox** [comment]
초기화면이 Merge 됨에 따라 이 Task도 Close 합니다.
