### ISSUE TITLE
[task] 교인 리스트 출력 (Back-end)

### ISSUE THREAD

**Issue by gyounlee** [jibyun/digital-okcc#9]
Client에서 주소록 리스트 요청시 DB로 부터 필요한 데이타를 읽어와서 리턴하는 모듈

**Comment by kwkim80** [comment]
SaintController 생성 후 index 액션에서 
DB를 파사드 형식으로 호출하여 saint리스트 모델을 만들어 
saint/index 뷰에 전달

**Comment by lifeisox** [comment]
파사드 사용하는 형식 말고, Eloquent ORM을 사용하는 방식도 실험해봐야 할 것 같아요.

**Comment by lifeisox** [comment]
Eloquent ORM 방식으로 교인 리스트 출력 완성하여 branch에 push하였습니다.

**Comment by gyounlee** [comment]
프로젝트의 리뷰단계는 현재 code review(pull request) 중인  task에 해당됩니다.
이미 개인적으로 구현해 보셨지만 실제 project에 해당되는 작업은 아닌 관계로 In Progress 또는 To do로 옮겨주시기 바랍니다.

**Comment by lifeisox** [comment]
그럼, 이 타스크는 이제 끝났으니 삭제하는 것으로 하시죠.

**Comment by gyounlee** [comment]
간단하게 교인리스트 출력하는 로직 구현
